spring:
  data:
    mongodb:
      username: root
      password: example
      database: upload
      host: localhost
      port: 27017
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1KB
      max-file-size: 200MB
      max-request-size: 215MB
      location: /home/kate/upload
server:
  port: 9092
kafka:
  consumer: localhost:9092
  group:
    id: request